# ref: https://yarnpkg.com/configuration/yarnrc
logFilters:
  - pattern: '.* The platform "darwin" is incompatible with this module.'
    level: discard
  - pattern: ".* is an optional dependency and failed compatibility check. Excluding it from installation."
    level: discard
  - pattern: '.* The CPU architecture "x64" is incompatible with this module.'
    level: discard
# the end
